name: PR for latest Syft release
on:
  schedule:
    - cron: "0 8 * * *" # 3 AM EST

  workflow_dispatch:

env:
  GO_VERSION: "1.21.x"

permissions:
  contents: read

jobs:
  upgrade-syft:
    runs-on: ubuntu-latest
    if: github.repository == 'xeol-io/xeol' # only run for main repo
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v2.5.0

      - uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
        with:
          go-version: ${{ env.GO_VERSION }}

      - run: |
          LATEST_VERSION=$(curl "https://api.github.com/repos/anchore/syft/releases/latest" 2>/dev/null | jq -r '.tag_name')

          # update go.mod
          go get github.com/anchore/syft@$LATEST_VERSION
          go mod tidy

          # export the version for use with create-pull-request
          echo "::set-output name=LATEST_VERSION::$LATEST_VERSION"
        id: latest-version

      - uses: tibdex/github-app-token@32691ba7c9e7063bd457bd8f2a5703138591fa58 # v1.9.0
        id: generate-token
        with:
          app_id: ${{ secrets.TOKEN_APP_ID }}
          private_key: ${{ secrets.TOKEN_APP_PRIVATE_KEY }}

      - uses: peter-evans/create-pull-request@c5a7806660adbe173f04e3e038b0ccdcd758773c # v6.1.0
        with:
          signoff: true
          delete-branch: true
          branch: auto/latest
          labels: dependencies
          commit-message: "Update Syft to ${{ steps.latest-version.outputs.LATEST_VERSION }}"
          title: "Update Syft to ${{ steps.latest-version.outputs.LATEST_VERSION }}"
          body: |
            Update Syft to ${{ steps.latest-version.outputs.LATEST_VERSION }}
          token: ${{ steps.generate-token.outputs.token }}
