name: PR for latest Syft release
# on:
#   schedule:
#     - cron: "0 8 * * *" # 3 AM EST

#   workflow_dispatch:
on:
  push:
    branches: [ "benji.visser/update-syft-release" ]
env:
  GO_VERSION: "1.18.x"

permissions:
  contents: read

jobs:
  upgrade-syft:
    runs-on: ubuntu-latest
    if: github.repository == 'noqcks/xeol' # only run for main repo
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v2.5.0

      - uses: actions/setup-go@c4a742cab115ed795e34d4513e2cf7d472deb55f # v3.3.1
        with:
          go-version: ${{ env.GO_VERSION }}

      - run: |
          LATEST_VERSION=$(curl "https://api.github.com/repos/anchore/syft/releases/latest" 2>/dev/null | jq -r '.tag_name')

          # update go.mod
          go get github.com/anchore/syft@$LATEST_VERSION
          go mod tidy

          # export the version for use with create-pull-request
          echo "::set-output name=LATEST_VERSION::$LATEST_VERSION"
        id: latest-version

      - uses: tibdex/github-app-token@021a2405c7f990db57f5eae5397423dcc554159c # v1.7.0
        id: generate-token
        with:
          app_id: ${{ secrets.TOKEN_APP_ID }}
          private_key: ${{ secrets.TOKEN_APP_PRIVATE_KEY }}

      - uses: peter-evans/create-pull-request@b4d51739f96fca8047ad065eccef63442d8e99f7 # v4.2.0
        with:
          signoff: true
          delete-branch: true
          branch: auto/latest
          labels: dependencies
          commit-message: "Update Syft to ${{ steps.latest-version.outputs.LATEST_VERSION }}"
          title: "Update Syft to ${{ steps.latest-version.outputs.LATEST_VERSION }}"
          body: |
            Update Syft to ${{ steps.latest-version.outputs.LATEST_VERSION }}
          token: ${{ steps.generate-token.outputs.token }}
